logging:
  level:
    com.yuqiyu.chapter12.controller: 'off'

#在application.yml配置文件内，off必须添加双引号，否则不会生效。
#LogBack读取配置文件的步骤
#（1）尝试classpath下查找文件logback-test.xml
#（2）如果文件不存在，尝试查找logback.xml
#（3）如果两个文件都不存在，LogBack用BasicConfiguration自动对自己进行最小化配置，这样既实现了上面我们不需要添加任何配置就可以输出到控制台日志信息。
